---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      # Step 1: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCERHUB_USER }}  # Ensure this secret is correctly set
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Ensure this secret is correctly set

      # Step 2: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 3: Run tests using Docker Compose
      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      # Step 4: Run linting using Docker Compose
      - name: Run Linting
        run: docker compose run --rm app sh -c "flake8"